services:
  fntv-douban-sync:
    build: .
    container_name: fntv-douban-sync
    ports:
      - "58080:5000"
    volumes:
      - /usr/local/apps/@appdata/trim.media/database/trimmedia.db:/fntv-db/trimmedia.db:ro
      - /vol1/1000/docker/doubansync/sync_state:/app/sync_state
    environment:
      - TZ=Asia/Shanghai
      - FNTV_DB_PATH=/fntv-db/trimmedia.db
    restart: unless-stopped
